language: go
go:
- 1.5
after_success:
- bin/build-all.sh
deploy:
  provider: releases
  api_key:
    secure: Xlhi926g2KpE+qGAT3RgxKL/NpdNk1mXVT9UEEEXF0rXvGxKhNQqp9kgJeIXq54FsEFPL2EmwXxq3uDLMkCzqlPaESl1icG+c+9BUyzajv9MNSDcEIpvSgAI/kqlUDY3CT7o713j17GJ/CrK+/OMsIb8St9xaONA6EsMTTucEAUM18vsRh6QZJ5gC8cLljKM+x4adNc/vr4kaTy/t7nilMGdm/tAk29ghbd5zLh2AQAVeR0mb8H4Z3lhUoxmpNkFpMtddfO1W/fcLXd8V87y8iaZu/hlziU2Wn0TuGwV3YVGlCNhsv4d3Q4gw+misaEzGc5QMwgO2EIOCoBm+mx7vGNsGw7giloy8rsyI7ENfj9lNp+RWVi2JyzJNgtXG0uNlbP5gUQ9O2Oh8ipJ2Xy/WBlcXq7jO81aJu7By+KprtyJIpCl3jnBl795YE8vvnpzCKY1w0NXuTzr+PR8bC7srKOxIHyzclnzkVVg9fhvrZ/yTBakwscjzVZG4AeiMXjvWNF+lz5YQMOXczPrS8Gqf3aeeyyceLf75zL6yAX9SmwqemXwdzm/S0xksBku2t8T25ZmGNn36ulu30QSCiPhh/DK9hMADQCrWwSJ4BSlvvtp7la6FESz7Ds8gC+ibh1UMVb6QSpnKHhdFhb/OXHnrwW79Zhsoc827L1u+6yORxQ=
  file:
  - out/github-blob-sender_darwin_amd64
  - out/github-blob-sender_linux_386
  - out/github-blob-sender_linux_amd64
  - out/github-blob-sender_linux_arm
  - out/github-blob-sender_windows_386.exe
  - out/github-blob-sender_windows_amd64.exe
  on:
    repo: ArthurHlt/github-blob-sender
    tags: true
    all_branches: true
